# Generated by Django 4.2.11 on 2024-05-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
