# Generated by Django 4.2.11 on 2024-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_response_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
    ]
